// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package person

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=FirstName,json=first_name,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=LastName,json=last_name,proto3" json:"LastName,omitempty"`
	Age                  uint32   `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  uint32   `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Person) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

type PersonX struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=LastName,proto3" json:"LastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonX) Reset()         { *m = PersonX{} }
func (m *PersonX) String() string { return proto.CompactTextString(m) }
func (*PersonX) ProtoMessage()    {}
func (*PersonX) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *PersonX) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonX.Unmarshal(m, b)
}
func (m *PersonX) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonX.Marshal(b, m, deterministic)
}
func (m *PersonX) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonX.Merge(m, src)
}
func (m *PersonX) XXX_Size() int {
	return xxx_messageInfo_PersonX.Size(m)
}
func (m *PersonX) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonX.DiscardUnknown(m)
}

var xxx_messageInfo_PersonX proto.InternalMessageInfo

func (m *PersonX) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *PersonX) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "person.Person")
	proto.RegisterType((*PersonX)(nil), "person.PersonX")
}

func init() {
	proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d)
}

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x32, 0xb8, 0xd8,
	0x02, 0xc0, 0x2c, 0x21, 0x59, 0x2e, 0x4e, 0xb7, 0xcc, 0xa2, 0xe2, 0x12, 0xbf, 0xc4, 0xdc, 0x54,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xae, 0x34, 0x90, 0x40, 0x7c, 0x5e, 0x62, 0x6e, 0xaa,
	0x90, 0x34, 0x17, 0x87, 0x4f, 0x22, 0x54, 0x96, 0x09, 0x2c, 0xcb, 0x99, 0x93, 0x08, 0x93, 0x14,
	0xe0, 0x62, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x0d, 0x02, 0x31, 0x41, 0x22,
	0xc5, 0xa9, 0x15, 0x12, 0x2c, 0x10, 0x91, 0xe2, 0xd4, 0x0a, 0x25, 0x67, 0x2e, 0x76, 0x88, 0x4d,
	0x11, 0x42, 0x32, 0x98, 0x56, 0x21, 0x04, 0x84, 0xa4, 0x30, 0x6c, 0x82, 0xf3, 0x93, 0xd8, 0xc0,
	0xae, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x77, 0x2c, 0x68, 0xbe, 0xcd, 0x00, 0x00, 0x00,
}
