// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: helloworldxx.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequestXX struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *HelloRequestXX) Reset() {
	*x = HelloRequestXX{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworldxx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequestXX) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequestXX) ProtoMessage() {}

func (x *HelloRequestXX) ProtoReflect() protoreflect.Message {
	mi := &file_helloworldxx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequestXX.ProtoReflect.Descriptor instead.
func (*HelloRequestXX) Descriptor() ([]byte, []int) {
	return file_helloworldxx_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequestXX) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type HelloReplyXX struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *HelloReplyXX) Reset() {
	*x = HelloReplyXX{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworldxx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReplyXX) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReplyXX) ProtoMessage() {}

func (x *HelloReplyXX) ProtoReflect() protoreflect.Message {
	mi := &file_helloworldxx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReplyXX.ProtoReflect.Descriptor instead.
func (*HelloReplyXX) Descriptor() ([]byte, []int) {
	return file_helloworldxx_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReplyXX) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_helloworldxx_proto protoreflect.FileDescriptor

var file_helloworldxx_proto_rawDesc = []byte{
	0x0a, 0x12, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x78, 0x78, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x78, 0x78, 0x22, 0x22, 0x0a, 0x0e,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x58, 0x58, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x20, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x58, 0x58,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x32, 0x65, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x5a, 0x0a,
	0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x26, 0x2e, 0x74, 0x72, 0x70, 0x63,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x78, 0x78, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x58,
	0x58, 0x1a, 0x24, 0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x78, 0x78, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x58, 0x58, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74,
	0x2e, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x6f, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x70,
	0x63, 0x2d, 0x67, 0x6f, 0x2f, 0x74, 0x72, 0x70, 0x63, 0x2d, 0x62, 0x65, 0x6e, 0x63, 0x68, 0x6d,
	0x61, 0x72, 0x6b, 0x2f, 0x62, 0x65, 0x6e, 0x63, 0x68, 0x6d, 0x61, 0x72, 0x6b, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_helloworldxx_proto_rawDescOnce sync.Once
	file_helloworldxx_proto_rawDescData = file_helloworldxx_proto_rawDesc
)

func file_helloworldxx_proto_rawDescGZIP() []byte {
	file_helloworldxx_proto_rawDescOnce.Do(func() {
		file_helloworldxx_proto_rawDescData = protoimpl.X.CompressGZIP(file_helloworldxx_proto_rawDescData)
	})
	return file_helloworldxx_proto_rawDescData
}

var file_helloworldxx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_helloworldxx_proto_goTypes = []interface{}{
	(*HelloRequestXX)(nil), // 0: trpc.test.helloworldxx.HelloRequestXX
	(*HelloReplyXX)(nil),   // 1: trpc.test.helloworldxx.HelloReplyXX
}
var file_helloworldxx_proto_depIdxs = []int32{
	0, // 0: trpc.test.helloworldxx.Greeter.SayHello:input_type -> trpc.test.helloworldxx.HelloRequestXX
	1, // 1: trpc.test.helloworldxx.Greeter.SayHello:output_type -> trpc.test.helloworldxx.HelloReplyXX
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworldxx_proto_init() }
func file_helloworldxx_proto_init() {
	if File_helloworldxx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_helloworldxx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequestXX); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworldxx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReplyXX); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_helloworldxx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworldxx_proto_goTypes,
		DependencyIndexes: file_helloworldxx_proto_depIdxs,
		MessageInfos:      file_helloworldxx_proto_msgTypes,
	}.Build()
	File_helloworldxx_proto = out.File
	file_helloworldxx_proto_rawDesc = nil
	file_helloworldxx_proto_goTypes = nil
	file_helloworldxx_proto_depIdxs = nil
}
